# Generated by Django 4.2.2 on 2023-09-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('pubdate', models.DateField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('rank', models.FloatField()),
            ],
        ),
    ]
