# Generated by Django 4.2.2 on 2023-09-25 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rank',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100),
        ),
    ]
